<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3wOZlq2' shared service.

return $this->privates['.service_locator.3wOZlq2'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'post' => function (): \App\Entity\Post {
    return ($this->privates['.errored..service_locator.3wOZlq2.App\\Entity\\Post'] ?? $this->load('getPostService.php'));
}, 'repo' => function (): \App\Repository\PostRepository {
    return ($this->privates['App\\Repository\\PostRepository'] ?? $this->load('getPostRepositoryService.php'));
}, 'repo1' => function (): \App\Repository\PostLikeRepository {
    return ($this->privates['App\\Repository\\PostLikeRepository'] ?? $this->load('getPostLikeRepositoryService.php'));
}]);
