<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v3DdqQH' shared service.

return $this->privates['.service_locator.v3DdqQH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['post' => function (): \App\Entity\Post {
    return ($this->privates['.errored..service_locator.v3DdqQH.App\\Entity\\Post'] ?? $this->load('getPostService.php'));
}, 'repo' => function (): \App\Repository\PostRepository {
    return ($this->privates['App\\Repository\\PostRepository'] ?? $this->load('getPostRepositoryService.php'));
}]);
