<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.v3DdqQH.App\Entity\Post' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.v3DdqQH": it references class "App\\Entity\\Post" but no such service exists.');
