<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPuCYN1Z\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPuCYN1Z/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPuCYN1Z.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPuCYN1Z\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPuCYN1Z\srcDevDebugProjectContainer([
    'container.build_hash' => 'PuCYN1Z',
    'container.build_id' => '2b63d8dd',
    'container.build_time' => 1594745294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPuCYN1Z');
